### PR TITLE
Feature/typescript

### PR DESCRIPTION
**Pull request by bertearazvan**
In this PR I am migrating all of the components to use `TypeScript`.

At the same time, it also closes the issue in the `gras-storybook` repo where the `ArgsTable` was not displaying the `Props of the components`. 

This was happening because `Storybook` uses a plugin `react-docgen-typescript-loader` which bundles the props in the form of docs for every component. Therefore, this plugin had to be also added when we are creating the bundle for our library.

### CODE REVIEW

**Review by JeroenDerks — COMMENTED** [review]
I see youre using `blue` as a link color. Is this the DHI secondary color `#00A4EC`?

**Comment by bertearazvan** [comment]
In order to use and _external theme_ we are using the `useTheme` hook together with the `ThemeProvider` inside every component. Fixed the color of the links as well in the previous commit @JeroenDerks. 

Now we have a stable TypeScript based library where we can add any components which can be styled from an external materialUI Theme. 
```
import { ThemeProvider } from '@material-ui/core'; // make sure the component is imported from /core and not from /core/styles
import { useTheme, Theme } from '@material-ui/core/styles';
const YourComponent = () => {
const theme: Theme = useTheme();
return (
<ThemeProvider theme={theme}>
     <YourMaterialUIComponents />
</ThemeProvider>
 )
}
export default YourComponent ;
```

**Review by Robert-OP — COMMENTED** [review]
👍

**Pull request merged**
